name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  audioplayers: ^6.5.1
  firebase_analytics: ^12.0.1
  firebase_core: ^4.1.0
  firebase_remote_config: ^6.0.1
  flutter:
    sdk: flutter
  google_fonts: ^6.3.1
  google_mobile_ads: ^5.1.0
  get_it: ^8.0.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  flutter_gen: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1

flutter_gen:
  output: lib/gen/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/icon.png
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
  # fonts:
  #   - family: PressStart2P
  #     fonts:
  #       - asset: assets/fonts/PressStart2P-Regular.ttf
