name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  audioplayers: ^6.5.1
  firebase_analytics: ^12.0.1
  firebase_core: ^4.1.0
  firebase_remote_config: ^5.1.3
  flutter:
    sdk: flutter
  google_fonts: ^6.3.1
  google_mobile_ads: ^6.0.0
  provider: ^6.1.5+1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
  # fonts:
  #   - family: PressStart2P
  #     fonts:
  #       - asset: assets/fonts/PressStart2P-Regular.ttf
